"""add_taskTemplate_and_calendar_api

Revision ID: 051c0e5db99d
Revises: 
Create Date: 2026-01-02 15:19:20.888420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051c0e5db99d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False, comment='グループ名'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_groups_group_id'), 'groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_groups_group_name'), 'groups', ['group_name'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    op.create_table('task_templates',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='テンプレートの管理名（例：定例会議）'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_task_templates_group_id'), 'task_templates', ['group_id'], unique=False)
    op.create_index(op.f('ix_task_templates_template_id'), 'task_templates', ['template_id'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_span_begin', sa.DateTime(), nullable=True),
    sa.Column('time_span_end', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_task', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True, comment='未着手、進行中、完了、None=タスクではない'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_group_id'), 'tasks', ['group_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=False)
    op.create_table('user_groups',
    sa.Column('user_group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('is_representative', sa.Boolean(), nullable=True, comment='代表者フラグ (True=代表/管理者)'),
    sa.Column('accepted', sa.Boolean(), nullable=True, comment='参加承認状態 (True=参加済み, False=承認待ち)'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_group_id'),
    sa.UniqueConstraint('user_id', 'group_id', name='unique_user_group_membership')
    )
    op.create_table('task_user_relations',
    sa.Column('relation_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_assigned', sa.Boolean(), nullable=True, comment='True: 担当者, False: 担当者でない'),
    sa.Column('reaction', sa.String(length=20), nullable=True, comment='join: 参加, absent: 不参加, undecided: 未定, no-reaction: 無反応'),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relation_id'),
    sa.UniqueConstraint('task_id', 'user_id', name='unique_task_user_membership')
    )
    op.create_index(op.f('ix_task_user_relations_relation_id'), 'task_user_relations', ['relation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_user_relations_relation_id'), table_name='task_user_relations')
    op.drop_table('task_user_relations')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_group_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_templates_template_id'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_group_id'), table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_groups_group_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_group_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###