"""add_slack_columns_to_group

Revision ID: bd2e5c83eb1c
Revises: dc677e0930d4
Create Date: 2026-01-04 13:38:54.632755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd2e5c83eb1c'
down_revision: Union[str, Sequence[str], None] = 'dc677e0930d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('slack_bot_token', sa.String(length=255), nullable=True))
    op.add_column('groups', sa.Column('slack_channel_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'slack_channel_id')
    op.drop_column('groups', 'slack_bot_token')
    # ### end Alembic commands ###