"""fixed_tables

Revision ID: dc677e0930d4
Revises: 051c0e5db99d
Create Date: 2026-01-03 16:24:38.074683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc677e0930d4'
down_revision: Union[str, Sequence[str], None] = '051c0e5db99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('unique_user_group_membership'), table_name='user_groups')
    op.drop_table('user_groups')
    op.create_index(op.f('ix_task_user_relations_task_id'), 'task_user_relations', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_user_relations_user_id'), 'task_user_relations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_user_relations_user_id'), table_name='task_user_relations')
    op.drop_index(op.f('ix_task_user_relations_task_id'), table_name='task_user_relations')
    op.create_table('user_groups',
    sa.Column('user_group_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('group_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('is_representative', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='代表者フラグ (True=代表/管理者)'),
    sa.Column('accepted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='参加承認状態 (True=参加済み, False=承認待ち)'),
    sa.Column('joined_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], name=op.f('user_groups_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_groups_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_group_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('unique_user_group_membership'), 'user_groups', ['user_id', 'group_id'], unique=True)
    # ### end Alembic commands ###